### ISSUE TITLE
<OverlayProvider>

### ISSUE THREAD

**Issue by streamich** [MailOnline/libreact#36]
Add an optional `<OverlayProvider>` component that will work together with `<Overlay>` component to provide better experience. It would we be a render prop that injects `disabled` prop into its child `<App>` component.

```js
<OverlayProvider component={App} />
```

This would allow `<App>` to set properly:

- `aria-hidden`
- inert
- `pointer-events: none`

Maybe also create generic `<App>` component that does all of that.

**Comment by azukaar** [comment]
Shouldn't it do

```
<OverlayProvider>
 <App />
</OverlayProvider>
```

**Comment by streamich** [comment]
@azukaar I have extracted interface creation in a separate lib:

https://github.com/streamich/react-universal-interface

**Comment by streamich** [comment]
Actually, maybe better create `<Modal>` component that uses `<Overlay>` internally, and `<ModalManager>` instead of `<OverlayProvider>`.

Also: https://www.youtube.com/watch?v=JS68faEUduk

**Comment by streamich** [comment]
Created `<Modal>` for now instead, here: https://github.com/MailOnline/libreact/pull/38
